export interface FeedMentorship {
  sqid: string
  title: string
  description: string
  category: string
  work_mode: 'Remote' | 'Onsite' | 'Hybrid'
  duration_weeks: number
  start_date: string
  end_date: string
  available_slots: number
  remaining_slots: number
  created_at: string
  alumnus: number
}

export interface FeedInternship {
  id: number
  sqid: string
  title: string
  description: string
  work_mode: 'Remote' | 'Onsite' | 'Hybrid'
  engagement_type: 'Full-time' | 'Part-time'
  location: string
  industry: string
  duration_weeks: number
  start_date: string
  end_date: string
  is_paid: boolean
  stipend: string
  available_slots: number
  remaining_slots: number
  skills_required: string[]
  require_resume: boolean
  require_cover_letter: boolean
  created_at: string
  alumnus: number
}

export const feedMentorships: FeedMentorship[] = [
  {
    created_at: '2026-02-04T19:52:03.203209Z',
    title: 'Frontend Development Mentorship',
    description:
      'Guided mentorship focused on building responsive user interfaces with modern frontend frameworks and best practices.',
    category: 'Web Development',
    work_mode: 'Remote',
    duration_weeks: 8,
    start_date: '2026-03-01',
    end_date: '2026-04-26',
    available_slots: 5,
    remaining_slots: 5,
    sqid: 'FrwMELk',
    alumnus: 3,
  },
  {
    created_at: '2026-02-04T19:52:16.782043Z',
    title: 'Backend Engineering Mentorship',
    description:
      'Hands-on mentorship covering API design, database modeling, authentication, and backend architecture.',
    category: 'Backend Development',
    work_mode: 'Remote',
    duration_weeks: 10,
    start_date: '2026-02-20',
    end_date: '2026-05-01',
    available_slots: 3,
    remaining_slots: 3,
    sqid: 'nLKnICb',
    alumnus: 3,
  },
  {
    created_at: '2026-02-04T19:52:31.444774Z',
    title: 'Mobile App Development Mentorship',
    description:
      'Learn how to build cross-platform mobile applications using Flutter, focusing on clean UI and state management.',
    category: 'Mobile Development',
    work_mode: 'Remote',
    duration_weeks: 12,
    start_date: '2026-03-10',
    end_date: '2026-06-02',
    available_slots: 4,
    remaining_slots: 4,
    sqid: 'YvlROih',
    alumnus: 3,
  },
  {
    created_at: '2026-02-04T19:52:46.787957Z',
    title: 'UI/UX Design Mentorship',
    description:
      'Mentorship centered on user experience research, wireframing, and interface design using industry-standard tools.',
    category: 'Design',
    work_mode: 'Remote',
    duration_weeks: 6,
    start_date: '2026-02-25',
    end_date: '2026-04-07',
    available_slots: 6,
    remaining_slots: 6,
    sqid: '8Qid2gD',
    alumnus: 3,
  },
  {
    created_at: '2026-02-04T19:53:01.397761Z',
    title: 'Cybersecurity Fundamentals Mentorship',
    description:
      'Introduction to cybersecurity concepts including threat modeling, basic network security, and defensive practices.',
    category: 'Cybersecurity',
    work_mode: 'Remote',
    duration_weeks: 8,
    start_date: '2026-03-05',
    end_date: '2026-04-30',
    available_slots: 2,
    remaining_slots: 2,
    sqid: 'tGj3JHa',
    alumnus: 3,
  },
  {
    created_at: '2026-02-04T19:53:09.519561Z',
    title: 'Data Analysis & Visualization Mentorship',
    description:
      'Mentorship on analyzing datasets, creating visualizations, and drawing insights using Python tools.',
    category: 'Data & Analytics',
    work_mode: 'Remote',
    duration_weeks: 7,
    start_date: '2026-03-15',
    end_date: '2026-05-03',
    available_slots: 3,
    remaining_slots: 3,
    sqid: 'AGtXW94',
    alumnus: 3,
  },
  {
    created_at: '2026-02-04T19:53:36.514247Z',
    title: 'DevOps & Cloud Basics Mentorship',
    description:
      'Learn the basics of CI/CD, containerization, and cloud deployment workflows through guided mentorship.',
    category: 'DevOps',
    work_mode: 'Remote',
    duration_weeks: 9,
    start_date: '2026-02-28',
    end_date: '2026-05-02',
    available_slots: 2,
    remaining_slots: 2,
    sqid: 'EZX6iHp',
    alumnus: 3,
  },
  {
    created_at: '2026-02-04T19:53:51.584507Z',
    title: 'Career & Technical Interview Mentorship',
    description:
      'Mentorship focused on CV reviews, technical interview preparation, and career guidance in the tech industry.',
    category: 'Career Development',
    work_mode: 'Remote',
    duration_weeks: 4,
    start_date: '2026-03-20',
    end_date: '2026-04-17',
    available_slots: 10,
    remaining_slots: 10,
    sqid: 'RSQHyAW',
    alumnus: 3,
  },
]

export const feedInternships: FeedInternship[] = [
  {
    id: 8,
    skills_required: ['Computer Hardware', 'Cable Management', 'Basic Linux'],
    created_at: '2026-02-04T10:36:02.254292Z',
    title: 'Technical Support Intern',
    description:
      'Provide hands-on technical assistance, help with hardware setup, and support internal IT infrastructure.',
    work_mode: 'Onsite',
    engagement_type: 'Part-time',
    location: 'Akure',
    industry: 'Technical Support',
    duration_weeks: 6,
    start_date: '2026-03-10',
    end_date: '2026-04-21',
    is_paid: true,
    stipend: '25000.00',
    available_slots: 3,
    remaining_slots: 3,
    require_resume: false,
    require_cover_letter: false,
    sqid: 'RSQHyAW',
    alumnus: 3,
  },
  {
    id: 7,
    skills_required: ['Linux', 'Shell Scripting', 'Server Monitoring'],
    created_at: '2026-02-04T10:35:42.331003Z',
    title: 'IT Operations Intern',
    description:
      'Support daily IT operations, monitor servers, and assist with routine maintenance and troubleshooting tasks.',
    work_mode: 'Onsite',
    engagement_type: 'Full-time',
    location: 'Akure',
    industry: 'IT Operations',
    duration_weeks: 10,
    start_date: '2026-02-25',
    end_date: '2026-05-06',
    is_paid: true,
    stipend: '40000.00',
    available_slots: 1,
    remaining_slots: 1,
    require_resume: true,
    require_cover_letter: true,
    sqid: 'EZX6iHp',
    alumnus: 3,
  },
  {
    id: 6,
    skills_required: [
      'System Administration',
      'Windows OS',
      'Basic Networking',
    ],
    created_at: '2026-02-04T10:35:04.252859Z',
    title: 'Junior Systems Support Intern',
    description:
      'Assist in managing computer systems, installing software, and providing first-level technical support to staff.',
    work_mode: 'Onsite',
    engagement_type: 'Full-time',
    location: 'Akure',
    industry: 'IT Support',
    duration_weeks: 8,
    start_date: '2026-03-01',
    end_date: '2026-04-26',
    is_paid: true,
    stipend: '35000.00',
    available_slots: 2,
    remaining_slots: 2,
    require_resume: true,
    require_cover_letter: false,
    sqid: 'AGtXW94',
    alumnus: 3,
  },
  {
    id: 5,
    skills_required: ['Networking', 'Hardware Troubleshooting', 'Linux'],
    created_at: '2026-02-04T04:05:09.647814Z',
    title: 'IT Support Intern',
    description:
      'Provide technical support, assist with hardware maintenance, and help manage internal IT systems.',
    work_mode: 'Onsite',
    engagement_type: 'Full-time',
    location: 'Akure',
    industry: 'IT Support',
    duration_weeks: 6,
    start_date: '2026-02-20',
    end_date: '2026-04-03',
    is_paid: true,
    stipend: '30000.00',
    available_slots: 2,
    remaining_slots: 2,
    require_resume: true,
    require_cover_letter: false,
    sqid: 'tGj3JHa',
    alumnus: 3,
  },
  {
    id: 4,
    skills_required: ['Python', 'Data Analysis', 'Pandas'],
    created_at: '2026-02-04T04:04:46.009984Z',
    title: 'Data Analysis Intern',
    description:
      'Analyze datasets, generate reports, and support data-driven decision-making within the organization.',
    work_mode: 'Remote',
    engagement_type: 'Full-time',
    location: 'Remote',
    industry: 'Data & Analytics',
    duration_weeks: 8,
    start_date: '2026-04-01',
    end_date: '2026-05-27',
    is_paid: true,
    stipend: '45000.00',
    available_slots: 1,
    remaining_slots: 1,
    require_resume: true,
    require_cover_letter: true,
    sqid: '8Qid2gD',
    alumnus: 3,
  },
  {
    id: 3,
    skills_required: ['UI/UX Design', 'Figma', 'Prototyping'],
    created_at: '2026-02-04T04:03:50.969550Z',
    title: 'UI/UX Design Intern',
    description:
      'Support the design team in creating user-friendly interfaces and improving user experience across platforms.',
    work_mode: 'Onsite',
    engagement_type: 'Part-time',
    location: 'Lagos',
    industry: 'Design',
    duration_weeks: 10,
    start_date: '2026-03-10',
    end_date: '2026-05-19',
    is_paid: false,
    stipend: '0.00',
    available_slots: 4,
    remaining_slots: 4,
    require_resume: false,
    require_cover_letter: false,
    sqid: 'YvlROih',
    alumnus: 3,
  },
  {
    id: 2,
    skills_required: ['Node.js', 'Express', 'MongoDB'],
    created_at: '2026-02-04T04:03:17.823405Z',
    title: 'Backend Engineering Intern',
    description:
      'Work with the backend team to design and implement APIs and database models for web applications.',
    work_mode: 'Remote',
    engagement_type: 'Full-time',
    location: 'Akure',
    industry: 'Information Technology',
    duration_weeks: 16,
    start_date: '2026-02-15',
    end_date: '2026-06-07',
    is_paid: true,
    stipend: '60000.00',
    available_slots: 2,
    remaining_slots: 2,
    require_resume: false,
    require_cover_letter: false,
    sqid: 'nLKnICb',
    alumnus: 3,
  },
]


import { Event, EventListItem, PurchasedTicket } from '@/types/event'

export const mockEvents: Event[] = [
  {
    sqid: 'evt001',
    title: 'Tech Career Workshop 2026',
    description:
      'Join us for an interactive workshop on navigating your tech career. Learn from industry experts about resume building, interview preparation, and networking strategies.',
    category: 'workshop',
    mode: 'virtual',
    venue: '',
    date: '2026-02-15',
    start_time: '10:00:00',
    duration_mins: 120,
    max_capacity: 100,
    allow_sponsorship: true,
    allow_donations: false,
    is_cancelled: false,
    is_published: true,
    created_at: '2026-01-20T08:00:00Z',
    updated_at: '2026-01-20T08:00:00Z',
    creator: 1,
    virtual_meeting: {
      sqid: 'vm001',
      platform: 'zoom',
      join_url: 'https://zoom.us/j/123456789',
      room_name: 'Tech Career Workshop',
    },
    starting_price: '0.00',
    tickets: [
      {
        sqid: 'tkt001',
        event: 'evt001',
        name: 'Free Entry',
        description: 'General admission',
        price: '0.00',
        sales_price: '0.00',
        discount_perc: '0',
        quantity: 100,
        quantity_sold: 45,
        type: 'default',
        sales_start: '2026-01-20T00:00:00Z',
        sales_end: '2026-02-14T23:59:59Z',
        is_active: true,
        created_at: '2026-01-20T08:00:00Z',
      },
    ],
  },
  {
    sqid: 'evt002',
    title: 'Alumni Networking Night',
    description:
      'Connect with fellow FUTA alumni across industries. Share experiences, build connections, and explore collaboration opportunities.',
    category: 'networking',
    mode: 'physical',
    venue: 'FUTA Alumni Center, Main Campus',
    date: '2026-03-10',
    start_time: '18:00:00',
    duration_mins: 180,
    max_capacity: 50,
    allow_sponsorship: true,
    allow_donations: true,
    is_cancelled: false,
    is_published: true,
    created_at: '2026-01-18T10:00:00Z',
    updated_at: '2026-01-18T10:00:00Z',
    creator: 1,
    starting_price: '2500.00',
    tickets: [
      {
        sqid: 'tkt002',
        event: 'evt002',
        name: 'Standard Ticket',
        description: 'Includes dinner and networking session',
        price: '2500.00',
        sales_price: '2500.00',
        discount_perc: '0',
        quantity: 40,
        quantity_sold: 28,
        type: 'default',
        sales_start: '2026-01-18T00:00:00Z',
        sales_end: '2026-03-09T23:59:59Z',
        is_active: true,
        created_at: '2026-01-18T10:00:00Z',
      },
      {
        sqid: 'tkt003',
        event: 'evt002',
        name: 'VIP Ticket',
        description: 'Premium seating and exclusive lounge access',
        price: '5000.00',
        sales_price: '5000.00',
        discount_perc: '0',
        quantity: 10,
        quantity_sold: 5,
        type: 'vip',
        sales_start: '2026-01-18T00:00:00Z',
        sales_end: '2026-03-09T23:59:59Z',
        is_active: true,
        created_at: '2026-01-18T10:00:00Z',
      },
    ],
  },
  {
    sqid: 'evt003',
    title: 'AI & Machine Learning Seminar',
    description:
      'Explore the latest trends in AI and Machine Learning. This hybrid event features keynote speakers from top tech companies.',
    category: 'seminar',
    mode: 'hybrid',
    venue: 'FUTA Auditorium',
    date: '2026-04-05',
    start_time: '09:00:00',
    duration_mins: 360,
    max_capacity: 200,
    allow_sponsorship: true,
    allow_donations: false,
    is_cancelled: false,
    is_published: true,
    created_at: '2026-01-15T14:00:00Z',
    updated_at: '2026-01-22T09:00:00Z',
    creator: 1,
    virtual_meeting: {
      sqid: 'vm002',
      platform: 'meet',
      join_url: 'https://meet.google.com/abc-defg-hij',
      room_name: 'AI Seminar 2026',
    },
    starting_price: '1000.00',
    tickets: [
      {
        sqid: 'tkt004',
        event: 'evt003',
        name: 'Online Access',
        description: 'Virtual attendance via Google Meet',
        price: '1000.00',
        sales_price: '1000.00',
        discount_perc: '0',
        quantity: 150,
        quantity_sold: 67,
        type: 'default',
        sales_start: '2026-01-15T00:00:00Z',
        sales_end: '2026-04-04T23:59:59Z',
        is_active: true,
        created_at: '2026-01-15T14:00:00Z',
      },
      {
        sqid: 'tkt005',
        event: 'evt003',
        name: 'In-Person Ticket',
        description: 'Physical attendance with lunch included',
        price: '3500.00',
        sales_price: '3500.00',
        discount_perc: '0',
        quantity: 50,
        quantity_sold: 30,
        type: 'default',
        sales_start: '2026-01-15T00:00:00Z',
        sales_end: '2026-04-04T23:59:59Z',
        is_active: true,
        created_at: '2026-01-15T14:00:00Z',
      },
    ],
  },
  {
    sqid: 'evt004',
    title: 'FUTA Career Fair 2026',
    description:
      'Annual career fair connecting students and alumni with top employers. Over 50 companies will be present for recruitment.',
    category: 'career_fair',
    mode: 'physical',
    venue: 'FUTA Sports Complex',
    date: '2026-05-20',
    start_time: '08:00:00',
    duration_mins: 480,
    max_capacity: 500,
    allow_sponsorship: true,
    allow_donations: true,
    is_cancelled: false,
    is_published: false,
    created_at: '2026-01-10T11:00:00Z',
    updated_at: '2026-01-25T16:00:00Z',
    creator: 1,
    starting_price: '0.00',
    tickets: [],
  },
]

export const mockEventListItems: EventListItem[] = mockEvents.map(
  ({ tickets, creator, ...rest }) => rest,
)

export const mockPurchasedTickets: PurchasedTicket[] = [
  {
    email: 'student@futa.edu.ng',
    ticket: mockEvents[0].tickets![0],
    ticket_uid: '550e8400-e29b-41d4-a716-446655440001',
    is_paid: true,
    checked_in: false,
    checked_in_at: null,
  },
  {
    email: 'student@futa.edu.ng',
    ticket: mockEvents[2].tickets![0],
    ticket_uid: '550e8400-e29b-41d4-a716-446655440002',
    is_paid: true,
    checked_in: false,
    checked_in_at: null,
  },
]
